name: Pass Data Between Jobs (Using outputs)

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      my_message: ${{ steps.set_output.outputs.message }}
    steps:
      - id: set_output
        run: echo "message=Hello from Job 1" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Print received value
        run: echo "ðŸ‘‰ Message from job1: ${{ needs.job1.outputs.my_message }}"